mutation{
  bulkInsertCategory{
    _id
    name
  }
  bulkInsertProduct{
    _id
    name
    price
  }
  bulkInsertCity{
    _id
    name
  }
  bulkInsertProfile{
    _id
    name
  }
  bulkInsertCostumer{
    _id
    firstName
    lastName
    birthday
  }
  bulkInsertAddress{
    _id
    address
  }
  bulkInsertCart{
    _id
  }
  bulkInsertCartDetail{
    _id
  }
  bulkInsertOrder{
    _id
  }
  bulkInsertOrderDetail{
    _id
  }
}